`timescale 1ns / 1ps
`include "defines.vh"
import cpu_types_pkg::*;

module LoadQueue #(
    parameter integer DEPTH = 4,
    parameter integer INDEX_W = (DEPTH > 1) ? $clog2(DEPTH) : 1
) (
    input  logic clk, input logic rstn,
    input  logic flush,
    input  logic recover_valid, input logic system_flush,
    input  uop_id_t recover_id,
    input  logic accept_valid, input lsu_entry_t accept_entry,
    output logic accept_ready,
    input  logic accept1_valid, input lsu_entry_t accept1_entry,
    output logic accept1_ready,
    output logic head_valid, output lsu_entry_t head_entry,
    input logic issue_mark, input logic pop,
    input uop_id_t pop_uop_id,
    output logic pop_match_valid,
    output logic [INDEX_W-1:0] pop_match_idx,
    output logic [DEPTH-1:0] unissued_vec,
    output lsu_entry_t entries_flat [0:DEPTH-1],
    input  logic [INDEX_W-1:0] issue_idx,
    output logic [DEPTH-1:0] valid_vec,
    output logic [DEPTH*32-1:0] addr_flat,
    output logic [$clog2(DEPTH+1)-1:0] occupancy
);
    localparam integer COUNT_W = $clog2(DEPTH + 1);
    lsu_entry_t entries [0:DEPTH-1];
    logic issued [0:DEPTH-1];
    logic [COUNT_W-1:0] count;
    integer i;
    integer q;
    integer flush_dst;
    integer match_search_i;
    integer match_count;
    logic pop_match_found;
    logic [INDEX_W-1:0] pop_match_idx_i;

    wire pop_do = pop && (count != 0);
    wire pop_match_do = pop_do && pop_match_found;
    wire pop_release = pop_match_do && !flush && !system_flush;
    wire accept_do = accept_valid && accept_ready;
    wire accept1_do = accept1_valid && accept1_ready;
    wire [COUNT_W:0] free_slots = (DEPTH - count) + pop_release;
    wire both_load_valid = accept_valid && accept1_valid;
    wire accept1_older = both_load_valid &&
                         uop_is_younger(accept_entry.uop_id,
                                        accept1_entry.uop_id);

    // Match the returned owner by full uop ID.  Keep this separate from the
    // queue-view process below: pop is generated by the DCache completion
    // path, while entries_flat/unissued_vec feed request selection.  Combining
    // both in one process creates a zero-delay event loop through the arbiter.
    always @(*) begin
        pop_match_found = 1'b0;
        pop_match_idx_i = '0;
        match_count = 0;
        if (pop_do) begin
            for (match_search_i = 0; match_search_i < DEPTH; match_search_i = match_search_i + 1) begin
                if ((match_search_i < count) &&
                    uop_id_equal(entries[match_search_i].uop_id, pop_uop_id)) begin
                    if (!pop_match_found) begin
                        pop_match_found = 1'b1;
                        pop_match_idx_i = match_search_i[INDEX_W-1:0];
                    end
                    match_count = match_count + 1;
                end
            end
        end
        pop_match_valid = pop_match_found;
        pop_match_idx = pop_match_idx_i;
    end

    // Admission readiness may reuse the slot released by the registered pop
    // owner.  The queue views below remain independent of pop, pop_uop_id,
    // issue_mark, and the completion path so they cannot close the arbiter
    // selection loop.
    always @(*) begin
        accept_ready = 1'b0;
        accept1_ready = 1'b0;
        if (!flush && !system_flush && (free_slots != 0)) begin
            if (free_slots >= 2) begin
                accept_ready = 1'b1;
                accept1_ready = 1'b1;
            end else if (!both_load_valid) begin
                accept_ready = accept_valid;
                accept1_ready = accept1_valid;
            end else if (accept1_older) begin
                accept1_ready = 1'b1;
            end else begin
                accept_ready = 1'b1;
            end
        end
    end

    // Read-only combinational queue views.  They intentionally have no
    // dependency on pop, pop_uop_id, issue_mark, or the completion path.
    always @(*) begin
        head_valid = !flush && !system_flush && (count != 0) && !issued[0];
        head_entry = '0;
        if (count != 0) head_entry = entries[0];
        valid_vec = '0;
        unissued_vec = '0;
        addr_flat = '0;
        occupancy = count;
        for (i = 0; i < DEPTH; i = i + 1) begin
            valid_vec[i] = !flush && !system_flush && (i < count);
            unissued_vec[i] = !flush && !system_flush && (i < count) && !issued[i];
            entries_flat[i] = entries[i];
            addr_flat[i*32 +: 32] = entries[i].address;
        end
    end

    always_ff @(posedge clk or negedge rstn) begin
        if (!rstn) begin
            count <= 0;
            for (q = 0; q < DEPTH; q = q + 1) begin
                entries[q] <= '0;
                issued[q] <= 1'b0;
            end
        end else if (system_flush || flush) begin
            flush_dst = 0;
            for (q = 0; q < DEPTH; q = q + 1) begin
                if (!(pop_match_do && (q == pop_match_idx_i)) &&
                    !system_flush && recover_valid && (q < count) &&
                    !uop_is_younger(entries[q].uop_id, recover_id)) begin
                    entries[flush_dst] <= entries[q];
                    issued[flush_dst] <= issued[q];
                    flush_dst = flush_dst + 1;
                end
            end
            for (q = 0; q < DEPTH; q = q + 1) begin
                if (q >= flush_dst) begin
                    entries[q] <= '0;
                    issued[q] <= 1'b0;
                end
            end
            count <= flush_dst;
        end else begin
            if (pop_match_do) begin
                for (q = 0; q < DEPTH-1; q = q + 1) begin
                    if (q >= pop_match_idx_i && q < count-1) begin
                        entries[q] <= entries[q+1];
                        issued[q] <= issued[q+1];
                    end else if (q >= count-1) begin
                        entries[q] <= '0;
                        issued[q] <= 1'b0;
                    end
                end
                entries[DEPTH-1] <= '0;
                issued[DEPTH-1] <= 1'b0;

                if (accept1_do && accept_do && accept1_older) begin
                    entries[count-1] <= accept1_entry;
                    entries[count-1].valid <= 1'b1;
                    issued[count-1] <= 1'b0;
                    entries[count] <= accept_entry;
                    entries[count].valid <= 1'b1;
                    issued[count] <= 1'b0;
                end else begin
                    if (accept_do) begin
                        entries[count-1] <= accept_entry;
                        entries[count-1].valid <= 1'b1;
                        issued[count-1] <= 1'b0;
                    end
                    if (accept1_do) begin
                        entries[count-1 + accept_do] <= accept1_entry;
                        entries[count-1 + accept_do].valid <= 1'b1;
                        issued[count-1 + accept_do] <= 1'b0;
                    end
                end
            end else if (!pop_match_do) begin
                if (accept1_do && accept_do && accept1_older) begin
                    entries[count] <= accept1_entry;
                    entries[count].valid <= 1'b1;
                    issued[count] <= 1'b0;
                    entries[count+1] <= accept_entry;
                    entries[count+1].valid <= 1'b1;
                    issued[count+1] <= 1'b0;
                end else begin
                    if (accept_do) begin
                        entries[count] <= accept_entry;
                        entries[count].valid <= 1'b1;
                        issued[count] <= 1'b0;
                    end
                    if (accept1_do) begin
                        entries[count + accept_do] <= accept1_entry;
                        entries[count + accept_do].valid <= 1'b1;
                        issued[count + accept_do] <= 1'b0;
                    end
                end
            end

            count <= count - pop_match_do + accept_do + accept1_do;

            if (issue_mark) begin
                if (pop_match_do) begin
                    if (issue_idx > pop_match_idx_i) begin
                        issued[issue_idx - 1] <= 1'b1;
                    end else if (issue_idx < pop_match_idx_i) begin
                        issued[issue_idx] <= 1'b1;
                    end
                end else begin
                    if (issue_idx < count) issued[issue_idx] <= 1'b1;
                end
            end
        end
    end

`ifndef SYNTHESIS
    always @(posedge clk) begin
        if (rstn && !flush && !system_flush) begin
            if (pop) begin
                if (count == 0)
                    $fatal(1, "LoadQueue pop while queue is empty!");
                if (!pop_match_found)
                    $fatal(1, "LoadQueue pop uop_id mismatch! pop_uop_id=%p not found in entries", pop_uop_id);
                if (match_count > 1)
                    $fatal(1, "LoadQueue pop uop_id duplicate match! pop_uop_id=%p matched %0d entries", pop_uop_id, match_count);
            end
        end
    end
`endif

endmodule
